STAGE_TO_ROUND = {
    "GROUP_STAGE": "group",
    "LAST_32": "R32",
    "LAST_16": "R16",
    "QUARTER_FINALS": "QF",
    "SEMI_FINALS": "SF",
    "THIRD_PLACE": "3rd",
    "FINAL": "final",
}

STATUS_TO_INTERNAL = {
    "TIMED": "scheduled",
    "SCHEDULED": "scheduled",
    "LIVE": "in_progress",
    "IN_PLAY": "in_progress",
    "INPLAY": "in_progress",
    "PAUSED": "in_progress",
    "FINISHED": "completed",
    "POSTPONED": "postponed",
    "CANCELLED": "cancelled",
    "SUSPENDED": "suspended",
}

TEAM_CODE_ALIASES = {
    "DZA": "ALG",
    "IRI": "IRN",
    "DRC": "COD",
}

TEAM_INFO_BY_CODE = {
    "MEX": {"id": 1, "nombre": "Mexico"},
    "KOR": {"id": 2, "nombre": "Korea Republic"},
    "RSA": {"id": 3, "nombre": "South Africa"},
    "CZE": {"id": 4, "nombre": "Czechia"},
    "CAN": {"id": 5, "nombre": "Canada"},
    "QAT": {"id": 6, "nombre": "Qatar"},
    "SUI": {"id": 7, "nombre": "Switzerland"},
    "BIH": {"id": 8, "nombre": "Bosnia-Herzegovina"},
    "BRA": {"id": 9, "nombre": "Brazil"},
    "HAI": {"id": 10, "nombre": "Haiti"},
    "SCO": {"id": 11, "nombre": "Scotland"},
    "MAR": {"id": 12, "nombre": "Morocco"},
    "USA": {"id": 13, "nombre": "USA"},
    "AUS": {"id": 14, "nombre": "Australia"},
    "PAR": {"id": 15, "nombre": "Paraguay"},
    "TUR": {"id": 16, "nombre": "Turkey"},
    "CIV": {"id": 17, "nombre": "Côte d'Ivoire"},
    "ECU": {"id": 18, "nombre": "Ecuador"},
    "GER": {"id": 19, "nombre": "Germany"},
    "CUW": {"id": 20, "nombre": "Curaçao"},
    "NED": {"id": 21, "nombre": "Netherlands"},
    "JPN": {"id": 22, "nombre": "Japan"},
    "TUN": {"id": 23, "nombre": "Tunisia"},
    "SWE": {"id": 24, "nombre": "Sweden"},
    "BEL": {"id": 25, "nombre": "Belgium"},
    "EGY": {"id": 26, "nombre": "Egypt"},
    "IRN": {"id": 27, "nombre": "IR Iran"},
    "NZL": {"id": 28, "nombre": "New Zealand"},
    "KSA": {"id": 29, "nombre": "Saudi Arabia"},
    "ESP": {"id": 30, "nombre": "Spain"},
    "URU": {"id": 31, "nombre": "Uruguay"},
    "CPV": {"id": 32, "nombre": "Cabo Verde"},
    "FRA": {"id": 33, "nombre": "France"},
    "SEN": {"id": 34, "nombre": "Senegal"},
    "NOR": {"id": 35, "nombre": "Norway"},
    "IRQ": {"id": 36, "nombre": "Iraq"},
    "ARG": {"id": 37, "nombre": "Argentina"},
    "ALG": {"id": 38, "nombre": "Algeria"},
    "AUT": {"id": 39, "nombre": "Austria"},
    "JOR": {"id": 40, "nombre": "Jordan"},
    "POR": {"id": 41, "nombre": "Portugal"},
    "UZB": {"id": 42, "nombre": "Uzbekistan"},
    "COL": {"id": 43, "nombre": "Colombia"},
    "COD": {"id": 44, "nombre": "Congo DR"},
    "GHA": {"id": 45, "nombre": "Ghana"},
    "PAN": {"id": 46, "nombre": "Panama"},
    "ENG": {"id": 47, "nombre": "England"},
    "CRO": {"id": 48, "nombre": "Croatia"},
}

INTERNAL_ID_BY_MATCH_NUMBER = {
    1: 2, 2: 1, 3: 7, 4: 20, 5: 15, 6: 19, 7: 13, 8: 9, 9: 28, 10: 26,
    11: 34, 12: 33, 13: 45, 14: 43, 15: 37, 16: 40, 17: 52, 18: 51,
    19: 58, 20: 55, 21: 70, 22: 68, 23: 61, 24: 63, 25: 3, 26: 8,
    27: 10, 28: 4, 29: 16, 30: 14, 31: 21, 32: 22, 33: 29, 34: 25,
    35: 31, 36: 35, 37: 44, 38: 47, 39: 38, 40: 41, 41: 53, 42: 49,
    43: 56, 44: 59, 45: 71, 46: 67, 47: 64, 48: 62, 49: 18, 50: 17,
    51: 12, 52: 11, 53: 6, 54: 5, 55: 30, 56: 27, 57: 32, 58: 36,
    59: 24, 60: 23, 61: 54, 62: 50, 63: 39, 64: 42, 65: 48, 66: 46,
    67: 69, 68: 72, 69: 57, 70: 60, 71: 66, 72: 65, 73: 82, 74: 93,
    75: 101, 76: 95, 77: 75, 78: 79, 79: 100, 80: 104, 81: 83, 82: 88,
    83: 98, 84: 81, 85: 97, 86: 86, 87: 91, 88: 78, 89: 89, 90: 94,
    91: 74, 92: 99, 93: 77, 94: 87, 95: 103, 96: 96, 97: 92, 98: 80,
    99: 85, 100: 90, 101: 76, 102: 102, 103: 84, 104: 73,
}

GROUP_MATCH_NUMBER_BY_TEAMS = {
    ("MEX", "RSA"): 1, ("KOR", "CZE"): 2, ("CAN", "BIH"): 3, ("USA", "PAR"): 4,
    ("HAI", "SCO"): 5, ("AUS", "TUR"): 6, ("BRA", "MAR"): 7, ("QAT", "SUI"): 8,
    ("CIV", "ECU"): 9, ("GER", "CUW"): 10, ("NED", "JPN"): 11, ("SWE", "TUN"): 12,
    ("KSA", "URU"): 13, ("ESP", "CPV"): 14, ("IRN", "NZL"): 15, ("BEL", "EGY"): 16,
    ("FRA", "SEN"): 17, ("IRQ", "NOR"): 18, ("ARG", "ALG"): 19, ("AUT", "JOR"): 20,
    ("GHA", "PAN"): 21, ("ENG", "CRO"): 22, ("POR", "COD"): 23, ("UZB", "COL"): 24,
    ("CZE", "RSA"): 25, ("SUI", "BIH"): 26, ("CAN", "QAT"): 27, ("MEX", "KOR"): 28,
    ("BRA", "HAI"): 29, ("SCO", "MAR"): 30, ("TUR", "PAR"): 31, ("USA", "AUS"): 32,
    ("GER", "CIV"): 33, ("ECU", "CUW"): 34, ("NED", "SWE"): 35, ("TUN", "JPN"): 36,
    ("URU", "CPV"): 37, ("ESP", "KSA"): 38, ("BEL", "IRN"): 39, ("NZL", "EGY"): 40,
    ("NOR", "SEN"): 41, ("FRA", "IRQ"): 42, ("ARG", "AUT"): 43, ("JOR", "ALG"): 44,
    ("ENG", "GHA"): 45, ("PAN", "CRO"): 46, ("POR", "UZB"): 47, ("COL", "COD"): 48,
    ("SCO", "BRA"): 49, ("MAR", "HAI"): 50, ("SUI", "CAN"): 51, ("BIH", "QAT"): 52,
    ("CZE", "MEX"): 53, ("RSA", "KOR"): 54, ("CUW", "CIV"): 55, ("ECU", "GER"): 56,
    ("JPN", "SWE"): 57, ("TUN", "NED"): 58, ("TUR", "USA"): 59, ("PAR", "AUS"): 60,
    ("NOR", "FRA"): 61, ("SEN", "IRQ"): 62, ("EGY", "IRN"): 63, ("NZL", "BEL"): 64,
    ("CPV", "KSA"): 65, ("URU", "ESP"): 66, ("PAN", "ENG"): 67, ("CRO", "GHA"): 68,
    ("ALG", "AUT"): 69, ("JOR", "ARG"): 70, ("COL", "POR"): 71, ("COD", "UZB"): 72,
}

KNOCKOUT_START_MATCH_NUMBER = {
    "R32": 73,
    "R16": 89,
    "QF": 97,
    "SF": 101,
    "3rd": 103,
    "final": 104,
}

STADIUM_BY_MATCH_NUMBER = {
    1: (14, "Estadio Azteca", "Mexico City", "Mexico"),
    2: (16, "Estadio Akron", "Guadalajara", "Mexico"),
    3: (13, "BMO Field", "Toronto, ON", "Canada"),
    4: (3, "SoFi Stadium", "Inglewood, CA", "USA"),
    5: (9, "Gillette Stadium", "Foxborough, MA", "USA"),
    6: (12, "BC Place", "Vancouver, BC", "Canada"),
    7: (1, "MetLife Stadium", "East Rutherford, NJ", "USA"),
    8: (4, "Levi's Stadium", "Santa Clara, CA", "USA"),
    9: (7, "Lincoln Financial Field", "Philadelphia, PA", "USA"),
    10: (10, "NRG Stadium", "Houston, TX", "USA"),
    11: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    12: (15, "Estadio BBVA", "Monterrey", "Mexico"),
    13: (5, "Hard Rock Stadium", "Miami Gardens, FL", "USA"),
    14: (17, "Mercedes-Benz Stadium", "Atlanta, GA", "USA"),
    15: (3, "SoFi Stadium", "Inglewood, CA", "USA"),
    16: (6, "Lumen Field", "Seattle, WA", "USA"),
    17: (1, "MetLife Stadium", "East Rutherford, NJ", "USA"),
    18: (9, "Gillette Stadium", "Foxborough, MA", "USA"),
    19: (8, "Arrowhead Stadium", "Kansas City, MO", "USA"),
    20: (4, "Levi's Stadium", "Santa Clara, CA", "USA"),
    21: (13, "BMO Field", "Toronto, ON", "Canada"),
    22: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    23: (10, "NRG Stadium", "Houston, TX", "USA"),
    24: (14, "Estadio Azteca", "Mexico City", "Mexico"),
    25: (17, "Mercedes-Benz Stadium", "Atlanta, GA", "USA"),
    26: (3, "SoFi Stadium", "Inglewood, CA", "USA"),
    27: (12, "BC Place", "Vancouver, BC", "Canada"),
    28: (16, "Estadio Akron", "Guadalajara", "Mexico"),
    29: (7, "Lincoln Financial Field", "Philadelphia, PA", "USA"),
    30: (9, "Gillette Stadium", "Foxborough, MA", "USA"),
    31: (4, "Levi's Stadium", "Santa Clara, CA", "USA"),
    32: (6, "Lumen Field", "Seattle, WA", "USA"),
    33: (13, "BMO Field", "Toronto, ON", "Canada"),
    34: (8, "Arrowhead Stadium", "Kansas City, MO", "USA"),
    35: (10, "NRG Stadium", "Houston, TX", "USA"),
    36: (15, "Estadio BBVA", "Monterrey", "Mexico"),
    37: (5, "Hard Rock Stadium", "Miami Gardens, FL", "USA"),
    38: (17, "Mercedes-Benz Stadium", "Atlanta, GA", "USA"),
    39: (3, "SoFi Stadium", "Inglewood, CA", "USA"),
    40: (12, "BC Place", "Vancouver, BC", "Canada"),
    41: (1, "MetLife Stadium", "East Rutherford, NJ", "USA"),
    42: (7, "Lincoln Financial Field", "Philadelphia, PA", "USA"),
    43: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    44: (4, "Levi's Stadium", "Santa Clara, CA", "USA"),
    45: (9, "Gillette Stadium", "Foxborough, MA", "USA"),
    46: (13, "BMO Field", "Toronto, ON", "Canada"),
    47: (10, "NRG Stadium", "Houston, TX", "USA"),
    48: (16, "Estadio Akron", "Guadalajara", "Mexico"),
    49: (5, "Hard Rock Stadium", "Miami Gardens, FL", "USA"),
    50: (17, "Mercedes-Benz Stadium", "Atlanta, GA", "USA"),
    51: (12, "BC Place", "Vancouver, BC", "Canada"),
    52: (6, "Lumen Field", "Seattle, WA", "USA"),
    53: (14, "Estadio Azteca", "Mexico City", "Mexico"),
    54: (15, "Estadio BBVA", "Monterrey", "Mexico"),
    55: (7, "Lincoln Financial Field", "Philadelphia, PA", "USA"),
    56: (1, "MetLife Stadium", "East Rutherford, NJ", "USA"),
    57: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    58: (8, "Arrowhead Stadium", "Kansas City, MO", "USA"),
    59: (3, "SoFi Stadium", "Inglewood, CA", "USA"),
    60: (4, "Levi's Stadium", "Santa Clara, CA", "USA"),
    61: (9, "Gillette Stadium", "Foxborough, MA", "USA"),
    62: (13, "BMO Field", "Toronto, ON", "Canada"),
    63: (6, "Lumen Field", "Seattle, WA", "USA"),
    64: (12, "BC Place", "Vancouver, BC", "Canada"),
    65: (10, "NRG Stadium", "Houston, TX", "USA"),
    66: (16, "Estadio Akron", "Guadalajara", "Mexico"),
    67: (1, "MetLife Stadium", "East Rutherford, NJ", "USA"),
    68: (7, "Lincoln Financial Field", "Philadelphia, PA", "USA"),
    69: (8, "Arrowhead Stadium", "Kansas City, MO", "USA"),
    70: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    71: (5, "Hard Rock Stadium", "Miami Gardens, FL", "USA"),
    72: (17, "Mercedes-Benz Stadium", "Atlanta, GA", "USA"),
    73: (3, "SoFi Stadium", "Inglewood, CA", "USA"),
    74: (9, "Gillette Stadium", "Foxborough, MA", "USA"),
    75: (15, "Estadio BBVA", "Monterrey", "Mexico"),
    76: (10, "NRG Stadium", "Houston, TX", "USA"),
    77: (1, "MetLife Stadium", "East Rutherford, NJ", "USA"),
    78: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    79: (14, "Estadio Azteca", "Mexico City", "Mexico"),
    80: (17, "Mercedes-Benz Stadium", "Atlanta, GA", "USA"),
    81: (4, "Levi's Stadium", "Santa Clara, CA", "USA"),
    82: (6, "Lumen Field", "Seattle, WA", "USA"),
    83: (13, "BMO Field", "Toronto, ON", "Canada"),
    84: (3, "SoFi Stadium", "Inglewood, CA", "USA"),
    85: (12, "BC Place", "Vancouver, BC", "Canada"),
    86: (5, "Hard Rock Stadium", "Miami Gardens, FL", "USA"),
    87: (8, "Arrowhead Stadium", "Kansas City, MO", "USA"),
    88: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    89: (7, "Lincoln Financial Field", "Philadelphia, PA", "USA"),
    90: (10, "NRG Stadium", "Houston, TX", "USA"),
    91: (1, "MetLife Stadium", "East Rutherford, NJ", "USA"),
    92: (14, "Estadio Azteca", "Mexico City", "Mexico"),
    93: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    94: (6, "Lumen Field", "Seattle, WA", "USA"),
    95: (17, "Mercedes-Benz Stadium", "Atlanta, GA", "USA"),
    96: (12, "BC Place", "Vancouver, BC", "Canada"),
    97: (9, "Gillette Stadium", "Foxborough, MA", "USA"),
    98: (3, "SoFi Stadium", "Inglewood, CA", "USA"),
    99: (5, "Hard Rock Stadium", "Miami Gardens, FL", "USA"),
    100: (8, "Arrowhead Stadium", "Kansas City, MO", "USA"),
    101: (2, "AT&T Stadium", "Arlington, TX", "USA"),
    102: (17, "Mercedes-Benz Stadium", "Atlanta, GA", "USA"),
    103: (5, "Hard Rock Stadium", "Miami Gardens, FL", "USA"),
    104: (1, "MetLife Stadium", "East Rutherford, NJ", "USA"),
}
